# Numpy Tutorial

In [1]:
import numpy as np

## One Dimensional Array

Let's first discuss one-dimensional arrays:

In [2]:
temp = [1, 2, 3, 4, 5]               # a list of integers
temp_array = np.array(temp)          # casting a list into a numpy-array
                                     # numpy-array is similar list, with each element of the same type

print(type(temp_array))              # temp_array is of type numpy.ndarray
print(temp_array[0], temp_array[4])  # indexing is similar to a list

<class 'numpy.ndarray'>
1 5


In [3]:
temp_array = np.array([2, 4, 6, 8])
print(temp_array.dtype)    # returns the data type of array elements
print(temp_array.size)     # returns the size of the array: total number of elements
print(temp_array.ndim)     # returns the dimensionality or rank of the array
print(temp_array.shape)    # returns a tuple, representing the size of array in each dimension

int64
4
1
(4,)


In [4]:
temp1 = np.array([1, 2])
temp2 = np.array([1, 3.14])
print(temp1.dtype, temp2.dtype)    # all elements are of same type
print(temp1)                       # all integers 
print(temp2)                       # all floats

int64 float64
[1 2]
[1.   3.14]


In [5]:
temp = np.array([1, 2, 3])
temp[0] = 100                     # arrays are mutable
temp

array([100,   2,   3])

In [6]:
temp = np.array([1, 2, 3])
temp[0:3] = 4, 5, 6         # assigning multiple elements 
temp                        # we can assign by a list or tuple also : [4, 5, 6] or (4, 5, 6)

array([4, 5, 6])

In [7]:
temp = np.array([1, 2, 3])
temp1 = temp[0:2]           # array can be sliced and assigned to a new array
temp1

array([1, 2])

In [8]:
temp = np.array([3.14, 6.28, 9.42])
indices = [0, 2]          # a list containing the indices
temp1 = temp[indices]     # we can select the elements present in 'temp' at 'indices'
temp1

array([3.14, 9.42])

In [9]:
temp = np.array([1, 2, 3])
indices = [0, 2]
temp[indices] = 100       # we can assign same number to all the selected indices
temp

array([100,   2, 100])

In [10]:
np.linspace(-2,2,5)   # np.linspace(start, end, num) returns num number of elements from start to end,
                      # including start and end both

array([-2., -1.,  0.,  1.,  2.])

In [11]:
temp1 = np.array([1, 2])
temp2 = np.array([3, 4])

print(temp1 + temp2)              # vector addition
print('-'*10)

print(temp1 * temp2)              # element-wise multiplication
print('-'*10)

print(np.dot(temp1, temp2))       # dot product
print('-'*10)

print(temp1 + 1)                  # broadcasting: adds one to each element
print('-'*10)

print(2*temp2)                    # scalar-vector multiplication: each element is multiplied by 2

[4 6]
----------
[3 8]
----------
11
----------
[2 3]
----------
[6 8]


In [12]:
temp = np.array([1, 2, 3])

print(temp.mean(), temp.std())  # returns the mean and standard deviation of the array
print(temp.min(), temp.max())   # returns the minimum and maximum of the array

2.0 0.816496580927726
1 3


In [13]:
temp = np.array([0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi]) # a numpy array of five elements
temp1 = np.sin(temp)  # returns an array, where element is sin of the original array element
temp1

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

## Multidimensional Array

Now, let's discuss multidimensional arrays

In [14]:
temp = [[11, 12], [21, 22], [31, 32]]   # a nested list
temp_array = np.array(temp)     # casting the nested list into a two dimensional numpy array: 
                                # each nested list corresponds to a row
print(temp_array)
print('-'*10)
print(temp_array[2,1])          # [i, j] returns the element at ith row and jth column

[[11 12]
 [21 22]
 [31 32]]
----------
32


In [15]:
temp = np.array([[11, 12], [21, 22], [31, 32]])

print(temp_array.ndim)     # returns the dimensionality/rank of the array
print(temp_array.shape)    # size of the array in each dimension: (nrows, ncolumns...)
print(temp_array.size)     # returns size of the array: total number of elements in the array

2
(3, 2)
6


In [16]:
temp = np.array([[11, 12], [21, 22], [31, 32]])

temp_array[1:3, 0:1]      # slicing an array

array([[21],
       [31]])

In [17]:
temp = np.array([[1, 2], [3, 4]])
2*temp                    # scalar-vector multiplication : each element of x1 is multiplied by 2

array([[2, 4],
       [6, 8]])

In [18]:
temp1 = np.array([[1, 2], [3, 4]])
temp2 = np.array([[5, 6], [7, 8]])

print(temp1 + temp2)              # element-wise addition
print('-'*10)

print(temp1 * temp2)              # element-wise multiplication
print('-'*10)

print(np.dot(temp1, temp2))       # matrix product
print('-'*10)
      
print(temp1.T)                    # transpose of a matrix

[[ 6  8]
 [10 12]]
----------
[[ 5 12]
 [21 32]]
----------
[[19 22]
 [43 50]]
----------
[[1 3]
 [2 4]]


# General 

In [19]:
rng = np.random.rand(5)        # generates an array of random numbers 
rng

array([0.59757677, 0.09113071, 0.52123989, 0.50117882, 0.14134288])